# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-04 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relatorio_despesas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('EST', 'Ped\xe1gio e Estacionamento'), ('FGB', 'Frigobar'), ('KM', 'Kilometragem'), ('LAV', 'Lavanderia'), ('BKF', 'Refei\xe7\xe3o - Caf\xe9 da manh\xe3'), ('ALM', 'Refei\xe7\xf5es - Almo\xe7o'), ('JAN', 'Refei\xe7\xf5es - Jantar'), ('LAN', 'Lanche'), ('TRP', 'Transporte'), ('TLF', 'Telefone')], max_length=50, verbose_name='Tipo')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('note', models.CharField(max_length=200, verbose_name='Observa\xe7\xf5es')),
                ('image', models.ImageField(upload_to=relatorio_despesas.models.get_upload_path, verbose_name='Foto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
