# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_despesas', '0001_Adding Expense model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observa\xe7\xf5es'),
        ),
    ]
