# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorio_despesas', '0002_Allowing blank note on expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, verbose_name='Saldo')),
                ('project', models.CharField(blank=True, max_length=50, verbose_name='Projeto')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agency', models.CharField(blank=True, max_length=10, verbose_name='Ag\xeancia')),
                ('account', models.CharField(blank=True, max_length=20, verbose_name='Conta corrente')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('EST', 'Ped\xe1gio e Estacionamento'), ('FGB', 'Frigobar'), ('KM', 'Kilometragem'), ('LAV', 'Lavanderia'), ('BKF', 'Caf\xe9 da manh\xe3'), ('REF', 'Refei\xe7\xe3o'), ('TRP', 'Transporte'), ('TLF', 'Telefone')], max_length=50, verbose_name='Tipo'),
        ),
    ]
