# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_despesas', '0003_Adding Employee model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Projeto'),
        ),
    ]
