# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import relatorio_despesas.models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_despesas', '0005_auto_20170407_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expensesFile',
            field=models.FileField(blank=True, null=True, upload_to=relatorio_despesas.models.get_upload_archive_path),
        ),
    ]
